// /ai.md: the AI assistants page as plain Markdown, built from the same data as /ai/.
import type { APIRoute } from "astro";
import { REPO } from "../data/catalogue";
import { agentRows, CLAUDE_CODE_CMD, CLAUDE_CODE_USER_CMD, CLI_LIST, CLI_RUN, MCP_JSON, NPM_URL, PROMPT, REGISTRY_NAME, REGISTRY_URL, SAFETY, WINDOWS_NOTE } from "../data/ai";

export const GET: APIRoute = async ({ site }) => {
  const abs = (p: string) => new URL(p, site).href;
  const rows = await agentRows();
  const lines = [
    "# Use these tools from your AI assistant",
    "",
    "Claude, ChatGPT, Cursor and other assistants can run these tools on your own computer, free and with no login, so your files are never uploaded.",
    "",
    "## Copy a prompt for your assistant",
    "",
    "````text",
    PROMPT,
    "````",
    "",
    "## Set it up",
    "",
    "You need Node.js 22 or later.",
    "",
    "### Claude Code",
    "",
    "```sh",
    CLAUDE_CODE_CMD,
    "```",
    "",
    "To use it in every project, run this instead:",
    "",
    "```sh",
    CLAUDE_CODE_USER_CMD,
    "```",
    "",
    "### Claude Desktop",
    "",
    "Open the Claude menu, then Settings, then Developer, then Edit Config. Add this block, save, and restart. Always give full file paths: Claude Desktop does not run in your project folder.",
    "",
    "```json",
    MCP_JSON,
    "```",
    "",
    WINDOWS_NOTE,
    "",
    "### Cursor",
    "",
    "Add the same block to `~/.cursor/mcp.json` for all projects, or `.cursor/mcp.json` in one project. Restart Cursor.",
    "",
    "### Another MCP client",
    "",
    "Find where the client lists local (stdio) servers. Set the command to `npx` and the arguments to `-y freethetools mcp`.",
    "",
    "### Without MCP",
    "",
    "Let the assistant run commands in a terminal.",
    "",
    "```sh",
    CLI_LIST,
    CLI_RUN,
    "```",
    "",
    "## What your assistant can do",
    "",
    "| Tool page | Agent tool name | Title |",
    "| --- | --- | --- |",
    ...rows.map((r) => `| [${r.page}](${abs(r.url)}) | \`${r.name}\` | ${r.title} |`),
    "",
    "Most image tools run on the website for now.",
    "",
    "## In the browser",
    "",
    "Each tool page offers its tool to assistants through WebMCP. Chrome and Edge support it in origin trials. Every job an assistant does is recorded in the person's Library, on their device.",
    "",
    "## Safety",
    "",
    ...SAFETY.map((s) => `- ${s}`),
    "- There is no hosted server, because your files would have to be uploaded.",
    "",
    "## For machines",
    "",
    `- ${abs("/llms.txt")}`,
    `- ${abs("/llms-full.txt")}`,
    `- ${abs("/api/tools.json")}`,
    `- npm: ${NPM_URL}`,
    `- MCP Registry: ${REGISTRY_NAME} at ${REGISTRY_URL}`,
    `- Source: ${REPO}`,
    "",
  ];
  return new Response(lines.join("\n"), { headers: { "Content-Type": "text/markdown; charset=utf-8" } });
};
